'use strict';

const CELL=42, MAP_W=10, MAP_H=7, CANVAS_W=CELL*MAP_W, CANVAS_H=CELL*MAP_H, SCREEN_W=520, SCREEN_H=760, MAP_X=50, MAP_Y=20, SCENE_X=50, SCENE_Y=15;
const SAVE_KEY='exio_roguelike_ver3_save_web';
const PASSWORD='0618';
const WEAPONS=[
{id:'borelli_knife',name:'ボレッリナイフ',atk:2,icon:'sword',tier:1,desc:'イタリア製のナイフ。'},
{id:'borelli_sword',name:'ボレッリソード',atk:6,icon:'sword',tier:2,desc:'イタリア製の剣。'},
{id:'borelli_blade',name:'ボレッリブレード',atk:11,icon:'sword',tier:3,desc:'イタリア製の大刀。'},
{id:'kamatani_sword',name:'カマタニの剣',atk:17,icon:'sword',tier:4,desc:'かつてエクシオを支配していたという伝説の魔剣。'}];
const ARMORS=[
{id:'borelli_shirt',name:'ボレッリシャツ',def:1,icon:'armor',tier:1,desc:'イタリア製のシャツ。'},
{id:'borelli_jacket',name:'ボレッリジャケット',def:4,icon:'armor',tier:2,desc:'イタリア製のジャケット。'},
{id:'borelli_coat',name:'ボレッリコート',def:8,icon:'armor',tier:3,desc:'イタリア製のコート。'},
{id:'su_misura_suit',name:'スミズーラのスーツ',def:13,icon:'armor',tier:4,desc:'職人が仕立てた特注品のスーツ。'}];
const ACCESSORIES=[
{id:'power_ring',name:'力の指輪',effect:'攻撃+3',icon:'ring',tier:1,desc:'攻撃力が上昇する指輪。'},
{id:'special_ring',name:'必殺の指輪',effect:'必殺ゲージ+30%',icon:'ring',tier:2,desc:'必殺技ゲージがたまりやすくなる指輪。'},
{id:'guard_ring',name:'守りの指輪',effect:'被ダメージ-2',icon:'ring',tier:3,desc:'受けるダメージを軽減する指輪。'},
{id:'heal_ring',name:'癒しの指輪',effect:'毎ターンHP回復',icon:'ring',tier:0,rare:true,desc:'戦闘中、ターン終了時にHPが自動回復する指輪。'}];
const ENEMY_DEFS=[
{id:'aya',name:'アヤネル',floor_min:1,floor_max:3,hp:68,atk:15},
{id:'mura',name:'ゴブリン村田',floor_min:1,floor_max:3,hp:78,atk:16},
{id:'tani',name:'反社タニオカ',floor_min:1,floor_max:3,hp:90,atk:17},
{id:'kuri',name:'クリタニー',floor_min:7,floor_max:9,hp:190,atk:34},
{id:'mae',name:'マエチャン',floor_min:4,floor_max:6,hp:128,atk:25},
{id:'abe',name:'プラズマ',floor_min:4,floor_max:6,hp:126,atk:24},
{id:'haya',name:'痛風魔人ハヤノ',floor_min:7,floor_max:9,hp:225,atk:37},
{id:'jun',name:'タバコ魔人ジュン',floor_min:7,floor_max:9,hp:215,atk:36},
{id:'kane',name:'闇商人カネコ',floor_min:4,floor_max:6,hp:140,atk:27}];
const BOSS_DEF={id:'ide2',name:'真・魔王イデラン',floor_min:10,floor_max:10,hp:610,atk:53,boss:true};
const OPENING=[
'エクシオ本社が入る巨大ビル\n「ラーズビル」。\n\nその最上階には、\nすべてを支配する社長\n「イデラン」が君臨している。',
'イデランを倒した者には\n莫大な報酬――\n\n『昇給』が与えられるという。',
'新進気鋭の若手社員\n「カワグチくん」は、\n\n昇給を勝ち取るため、\nラーズビルへと足を踏み入れた。',
'立ちはだかる社員たちを倒し、\n装備を集め、\nラーズビル最上階を目指せ。\n\n社長イデランを倒し、\n昇給を勝ち取れ！'];
const assetNames=['op_title','opev_scene','ed_scene','gameover_screen','floor','wall','chest','stairs','shop','player_down','player_left','player_right','player_up','armor','bomb','gold','kaihukuyaku','kemuridama','ring','sword','abe_map','aya_map','haya_map','ide2_map','jun_map','kane_map','kuri2_map','kuri_map','mae_map','mura_map','tani_map','abe_battle','aya_battle','haya_battle','ide_battle','ide2_battle','jun_battle','kane_battle','kuri2_battle','kuri_battle','mae_battle','mura_battle','shop_battle','tani_battle'];
const assetPath = k => `${k}.png`;
const rnd=(a,b)=>Math.floor(Math.random()*(b-a+1))+a, choice=a=>a[Math.floor(Math.random()*a.length)], clone=o=>o?JSON.parse(JSON.stringify(o)):null;

class Game{
 constructor(){this.canvas=document.getElementById('gameCanvas');this.ctx=this.canvas.getContext('2d');this.wrap=document.getElementById('gameWrap');this.statusEl=document.getElementById('status');this.logEl=document.getElementById('log');this.commandsEl=document.getElementById('commands');this.menuEl=document.getElementById('menuButtons');this.modal=document.getElementById('modal');this.fadeEl=document.getElementById('fade');if(this.fadeEl)this.fadeEl.style.transition='opacity .48s';this.passwordPanel=document.getElementById('passwordPanel');this.passwordInput=document.getElementById('passwordInput');this.passwordButton=document.getElementById('passwordButton');this.passwordError=document.getElementById('passwordError');this.assets={};this.passwordOk=sessionStorage.getItem('exio_pw_ok')==='1';this.bind();this.initState();this.loadAssets().then(()=>{this.newFloor();this.screen_mode=this.passwordOk?'title':'password';this.drawAll();});}
 async loadAssets(){await Promise.all(assetNames.map(k=>new Promise(res=>{const img=new Image();img.onload=()=>{this.assets[k]=img;res()};img.onerror=()=>res();img.src=assetPath(k);})));}
 bind(){if(this.passwordButton){this.passwordButton.onclick=()=>this.submitPassword();this.passwordInput.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();this.submitPassword()} e.stopPropagation();});this.passwordInput.addEventListener('input',()=>{this.passwordError.textContent='';});}
 document.querySelectorAll('#dpad button').forEach(b=>b.onclick=()=>{const [dx,dy]=b.dataset.move.split(',').map(Number);this.move(dx,dy)});window.addEventListener('keydown',e=>{if(e.target&&['INPUT','TEXTAREA'].includes(e.target.tagName))return;if(this.modal&&!this.modal.hidden&&e.key==='Escape'){this.closeModal();return} if(e.key==='ArrowUp'){e.preventDefault();this.move(0,-1)} if(e.key==='ArrowDown'){e.preventDefault();this.move(0,1)} if(e.key==='ArrowLeft'){e.preventDefault();this.leftKey()} if(e.key==='ArrowRight'){e.preventDefault();this.rightKey()} if(e.key==='Enter'){e.preventDefault();this.enterKey()} if(e.key==='Escape'){e.preventDefault();this.escKey()}});this.canvas.addEventListener('click',e=>this.canvasClick(e));}
 initState(){this.floor=1;this.level=1;this.exp=0;this.next_exp=20;this.max_hp=100;this.hp=100;this.atk_base=10;this.def_base=0;this.special=0;this.gold=0;this.potions=3;this.bombs=1;this.smokes=1;this.weapon=clone(WEAPONS[0]);this.armor=null;this.accessory=null;this.inventory_weapons=[this.weapon];this.inventory_armors=[];this.inventory_accessories=[];this.player=[1,1];this.player_direction='down';this.stairs=[8,5];this.shop=null;this.enemies=[];this.treasures=[];this.in_battle=false;this.in_shop=false;this.shop_confirm=null;this.enemy=null;this.enemy_hp=0;this.enemy_max_hp=0;this.enemy_atk=0;this.player_turn=true;this.battle_result_mode=false;this.defeated_enemy=null;this.pending_result_text='';this.last_log_text='';this.player_guard=false;this.player_skip_turn=false;this.enemy_turn_count=0;this.enemy_defending=false;this.game_cleared=false;this.screen_mode='title';this.title_index=0;this.opening_index=0;this.event_texts=[];this.event_index=0;this.event_next=null;this.spawn_counter=0;this.shop_stock={};}
 get atk(){let v=this.atk_base;if(this.weapon)v+=this.weapon.atk+this.enhanceBonus(this.weapon);if(this.accessory?.id==='power_ring')v+=this.accessoryLevelValue(this.accessory);return v}
 get defense(){let v=this.def_base;if(this.armor)v+=this.armor.def+this.enhanceBonus(this.armor);return v}
 floorName(){return this.floor>=10?'ラーズビル最上階':`ラーズビル${this.floor}階`}
 enhancedName(item){if(!item)return 'なし';const lv=this.enhanceLevel(item);return lv>0?`${item.name}+${lv}`:item.name}
 enhanceLevel(item){return item?.enhance||0} enhanceBonus(item){return this.enhanceLevel(item)*2} accessoryLevelValue(item){if(!item)return 0;const lv=this.enhanceLevel(item);if(item.id==='power_ring')return 3+lv*2;if(item.id==='special_ring')return 30+lv*10;if(item.id==='guard_ring')return 2+lv*2;if(item.id==='heal_ring')return 5+lv*3;return 0}
 log(t){this.last_log_text=t;this.logEl.textContent=t||''} appendLog(t){this.log((this.last_log_text?this.last_log_text+'\n':'')+t)}
 getCandidates(){return ENEMY_DEFS.filter(e=>this.floor>=e.floor_min&&this.floor<=e.floor_max)} maxEnemies(){return this.floor<=3?3:this.floor<=6?4:5}
 createEnemy(d,pos){return {...clone(d),x:pos[0],y:pos[1],awake:false,sleep:0}}
 newFloor(){this.player=[1,1];this.map=Array.from({length:MAP_H},(_,y)=>Array.from({length:MAP_W},(_,x)=>x===0||y===0||x===MAP_W-1||y===MAP_H-1?1:0));let wallCount=Math.min(4+Math.floor(this.floor/2),10),placed=0,tries=0;while(placed<wallCount&&tries++<300){let [x,y]=this.randomEmpty();if(Math.abs(x-1)+Math.abs(y-1)<=2)continue;this.map[y][x]=1;if(this.mapConnected())placed++;else this.map[y][x]=0}this.stairs=this.randomFar(7);this.shop=null;this.shop_stock={};if([3,5,7,9].includes(this.floor)){this.shop=this.randomFar(4);this.shop_stock={potion:true,bomb:true,smoke:true,weapon:true,armor:true,accessory:true}}this.enemies=[];if(this.floor>=10){this.enemies.push(this.createEnemy(BOSS_DEF,this.randomFar(6)));this.treasures=[];this.shop=null;this.log('屋上直下に到達した。\n魔王イデランの気配がする……')}else{let c=this.getCandidates().sort(()=>Math.random()-.5);c.slice(0,Math.min(this.maxEnemies(),c.length)).forEach(d=>this.enemies.push(this.createEnemy(d,this.randomFar(5))));this.treasures=[];for(let i=0;i<2;i++){let p=this.randomEmptyList();this.treasures.push({x:p[0],y:p[1]});}this.log(`${this.floorName()}に到着した。`)}this.drawAll()}
 randomEmpty(){for(let i=0;i<200;i++){let x=rnd(1,MAP_W-2),y=rnd(1,MAP_H-2);if(this.map[y][x]===0)return [x,y]}return [1,1]}
 randomEmptyList(){for(let i=0;i<200;i++){let [x,y]=this.randomEmpty();if(this.player[0]===x&&this.player[1]===y)continue;if(this.stairs[0]===x&&this.stairs[1]===y)continue;if(this.shop&&this.shop[0]===x&&this.shop[1]===y)continue;if(this.enemies.some(e=>e.x===x&&e.y===y))continue;if(this.treasures.some(t=>t.x===x&&t.y===y))continue;return [x,y]}return [1,1]}
 randomFar(min=5){let cs=[];for(let y=1;y<MAP_H-1;y++)for(let x=1;x<MAP_W-1;x++){if(this.map[y][x]!==0)continue;if(this.player[0]===x&&this.player[1]===y)continue;if(this.enemies.some(e=>e.x===x&&e.y===y)||this.treasures.some(t=>t.x===x&&t.y===y))continue;if(this.stairs&&this.stairs[0]===x&&this.stairs[1]===y)continue;if(this.shop&&this.shop[0]===x&&this.shop[1]===y)continue;if(Math.abs(x-this.player[0])+Math.abs(y-this.player[1])>=min)cs.push([x,y])}return cs.length?choice(cs):this.randomEmptyList()}
 mapConnected(){let st=[1,1],seen=new Set(['1,1']),stack=[st],total=0;for(let y=0;y<MAP_H;y++)for(let x=0;x<MAP_W;x++)if(this.map[y][x]===0)total++;while(stack.length){let [x,y]=stack.pop();[[1,0],[-1,0],[0,1],[0,-1]].forEach(([dx,dy])=>{let nx=x+dx,ny=y+dy,k=nx+','+ny;if(nx>=0&&ny>=0&&nx<MAP_W&&ny<MAP_H&&this.map[ny][nx]===0&&!seen.has(k)){seen.add(k);stack.push([nx,ny])}})}return seen.size===total}
 isWall(x,y){return x<0||y<0||x>=MAP_W||y>=MAP_H||this.map[y][x]===1}
 getEnemyAt(x,y){return this.enemies.find(e=>e.x===x&&e.y===y)} getTreasureAt(x,y){return this.treasures.find(t=>t.x===x&&t.y===y)}
 drawAll(){this.wrap.className='';this.canvas.width=SCREEN_W;this.canvas.height=SCREEN_H;if(this.passwordPanel){this.passwordPanel.hidden=this.screen_mode!=='password';if(this.screen_mode==='password')setTimeout(()=>this.passwordInput&&this.passwordInput.focus(),0);}if(['title','opening','gameover','boss_event','ending','password'].includes(this.screen_mode)){this.wrap.classList.add('fullScreenMode')}else if(this.in_battle){this.wrap.classList.add('battleMode')}else if(this.in_shop){this.wrap.classList.add('shopMode')}this.drawScene();this.drawStatus();this.drawCommands()}
 clear(){this.ctx.clearRect(0,0,SCREEN_W,SCREEN_H)} txt(text,x,y,size=14,color='white',align='center',base='middle',bold=true,maxWidth){let c=this.ctx;c.fillStyle=color;c.font=`${bold?'bold ':''}${size}px 'MS Gothic','Yu Gothic',monospace`;c.textAlign=align;c.textBaseline=base;String(text).split('\n').forEach((line,i)=>c.fillText(line,x,y+i*size*1.45,maxWidth));}
 rect(x,y,w,h,fill,stroke,width=1){let c=this.ctx;c.fillStyle=fill;c.fillRect(x,y,w,h);if(stroke){c.strokeStyle=stroke;c.lineWidth=width;c.strokeRect(x,y,w,h)}}
 drawImg(key,x,y,w,h,anchor='nw'){let img=this.assets[key];if(!img)return false;if(anchor==='center')this.ctx.drawImage(img,x-w/2,y-h/2,w,h);else this.ctx.drawImage(img,x,y,w,h);return true}
 bar(x,y,w,h,val,max,color){this.rect(x,y,w,h,'#444','#888');this.rect(x,y,w*Math.max(0,Math.min(1,val/max)),h,color)}
 drawScene(){if(this.screen_mode==='password')return this.drawPassword();if(this.screen_mode==='title')return this.drawTitle();if(this.screen_mode==='opening')return this.drawOpening();if(this.screen_mode==='gameover')return this.drawGameover();if(this.screen_mode==='boss_event')return this.drawBossEvent();if(this.screen_mode==='ending')return this.drawEnding();if(this.in_battle)return this.drawBattle();if(this.in_shop)return this.drawShop();return this.drawMap()}
 drawPassword(){this.clear();this.rect(0,0,SCREEN_W,SCREEN_H,'#000');this.txt('PASSWORD',260,210,34,'#ffca28');this.txt('ゲームを始めるにはパスワードを入力',260,265,15,'white')}
 drawTitle(){this.clear();this.drawImg('op_title',0,0,520,760);['はじめから','つづきから'].forEach((it,i)=>{let s=this.title_index===i;this.txt(`${s?'▶':'　'} ${it}`,262,612+i*46+2,23,'#000');this.txt(`${s?'▶':'　'} ${it}`,260,610+i*46,23,s?'#ffca28':'white')})}
 drawOpening(){this.clear();this.rect(0,0,520,760,'#000');this.drawImg('opev_scene',260,235,420,280,'center');this.rect(28,472,464,218,'#000','#fff',2);this.txt(OPENING[Math.min(this.opening_index,3)],50,492,19,'white','left','top',true,420);this.txt('▼',474,662,18,'#ffca28')}
 drawGameover(){this.clear();if(!this.drawImg('gameover_screen',0,0,520,760)){this.rect(0,0,520,760,'#000');this.txt('GAME OVER',260,240,42,'#b71c1c')}this.txt('▶ タイトルへ戻る',262,652,22,'#000');this.txt('▶ タイトルへ戻る',260,650,22,'#ffca28')}
 drawBossEvent(){this.clear();this.rect(0,0,520,760,'#000');this.drawImg('opev_scene',260,235,420,280,'center');this.rect(28,472,464,218,'#000','#fff',2);this.txt(this.event_texts[Math.min(this.event_index,this.event_texts.length-1)]||'',50,494,19,'white','left','top',true,420);this.txt('▼',474,662,18,'#ffca28')}
 drawEnding(){this.clear();this.drawImg('ed_scene',0,0,520,760);this.rect(28,570,464,135,'#000','#fff',2);this.txt('カワグチくんは\n見事ラーズビルを踏破し、\n昇給を勝ち取った！',50,596,20,'white','left','top');this.txt('クリック / Enter でタイトルへ',260,724,16,'#ffca28')}
 drawMap(){this.clear();for(let y=0;y<MAP_H;y++)for(let x=0;x<MAP_W;x++){this.drawImg('floor',MAP_X+x*CELL,MAP_Y+y*CELL,CELL,CELL);if(this.map[y][x]===1)this.drawImg('wall',MAP_X+x*CELL,MAP_Y+y*CELL,CELL,CELL)}if(this.shop)this.drawToken(this.shop[0],this.shop[1],'店','shop');this.treasures.forEach(t=>this.drawToken(t.x,t.y,'宝','chest'));this.enemies.forEach(e=>this.drawToken(e.x,e.y,'敵',`${e.id}_map`));this.drawToken(this.stairs[0],this.stairs[1],'階','stairs');this.drawToken(this.player[0],this.player[1],'自',`player_${this.player_direction}`)}
 drawToken(x,y,text,asset){if(this.drawImg(asset,MAP_X+x*CELL,MAP_Y+y*CELL,CELL,CELL))return;this.ctx.beginPath();this.ctx.arc(MAP_X+x*CELL+21,MAP_Y+y*CELL+21,15,0,Math.PI*2);this.ctx.fillStyle='#ef5350';this.ctx.fill();this.ctx.strokeStyle='#fff';this.ctx.stroke();this.txt(text,MAP_X+x*CELL+21,MAP_Y+y*CELL+21,12,'#000')}
 drawBattle(){this.clear();this.ctx.save();this.ctx.translate(SCENE_X,SCENE_Y);this.rect(0,0,420,405,'#101010');this.rect(12,12,396,381,'transparent','#777',2);if(this.battle_result_mode){this.rect(36,62,348,208,'#000','#ffca28',3);this.txt('VICTORY',210,96,30,'#ffca28');this.txt(this.pending_result_text,210,150,18,'white');}else{this.txt(this.enemy?.name||'',210,28,20);if(this.enemy){this.bar(62,54,296,15,this.enemy_hp,this.enemy_max_hp,'#ef5350');let key=`${this.enemy.id}_battle`;this.drawImg(key,210,this.enemy.id==='jun'?205:185,240,240,'center')}}this.rect(26,318,368,72,'#0b0b0b','#666');this.txt('カワグチくん',44,336,16,'white','left');this.txt('HP',44,361,13,'white','left');this.bar(92,352,226,17,this.hp,this.max_hp,'#66bb6a');this.txt(`${this.hp}/${this.max_hp}`,330,361,13,'white','left');this.txt('必殺',44,383,13,'#80deea','left');this.bar(92,374,226,17,this.special,100,'#26c6da');this.txt(this.special>=100?'使用可能':`${this.special}/100`,330,383,13,'#80deea','left');this.ctx.restore()}
 drawShop(){this.clear();this.ctx.save();this.ctx.translate(SCENE_X,SCENE_Y);this.rect(0,0,420,405,'#100c08');this.rect(14,14,392,377,'transparent','#8d6e63',3);this.txt('SHOP',210,36,25,'#ffca28');this.drawImg('shop_battle',210,158,180,180,'center');this.txt('必要なものを買っていきな。',210,292,18);this.rect(42,322,336,52,'#000','#666');this.txt(`所持金：${this.gold}G`,62,348,18,'#ffca28','left');this.txt(`薬:${this.potions} 爆:${this.bombs} 煙:${this.smokes}`,358,348,14,'white','right');this.ctx.restore()}
 drawStatus(){if(['title','opening','gameover','boss_event','ending','password'].includes(this.screen_mode))return;this.statusEl.textContent=`${this.floorName()}　Lv${this.level}　EXP ${this.exp}/${this.next_exp}\nHP ${this.hp}/${this.max_hp}　攻撃 ${this.atk}　防御 ${this.defense}　必殺 ${this.special}/100\n次のLvまで ${Math.max(0,this.next_exp-this.exp)}EXP`;}
 drawCommands(){this.commandsEl.innerHTML='';this.menuEl.innerHTML='';if(['title','opening','gameover','boss_event','ending','password'].includes(this.screen_mode))return;if(this.in_battle){if(this.battle_result_mode){this.commandsEl.innerHTML='<button class="wideBtn">探索へ戻る</button>';this.commandsEl.querySelector('button').onclick=()=>this.finishBattleResult();return}let log=document.createElement('div');log.className='battleLog';log.textContent=this.last_log_text;this.commandsEl.appendChild(log);let turn=document.createElement('div');turn.textContent=this.player_turn?'カワグチくんのターン':'敵のターン';turn.style.color=this.player_turn?'#80deea':'#ff8a80';turn.style.margin='2px 0 8px';this.commandsEl.appendChild(turn);let grid=document.createElement('div');grid.className='cmdGrid';['たたかう','ひっさつ','ぼうぎょ','アイテム','装備','逃げる'].forEach((n,i)=>{let b=document.createElement('button');b.textContent=n;if(n==='ひっさつ'&&this.special>=100)b.style.background='#00695c';b.disabled=!this.player_turn;b.onclick=()=>this.battleCommand(i);grid.appendChild(b)});this.commandsEl.appendChild(grid);return}if(this.in_shop){let grid=document.createElement('div');grid.className='shopGrid';['買う','売る','装備','強化'].forEach((n,i)=>{let b=document.createElement('button');b.textContent=n;b.onclick=()=>[()=>this.showBuy(),()=>this.showSell(),()=>this.showEquipment(),()=>this.showEnhance()][i]();grid.appendChild(b)});let out=document.createElement('button');out.textContent='店を出る';out.className='wideBtn';out.onclick=()=>{this.in_shop=false;this.log('店を出た。');this.drawAll()};this.commandsEl.append(grid,out);return}this.commandsEl.innerHTML=`<div class="exploreEquip">探索中<br>⚔ ${this.enhancedName(this.weapon)}<br>🛡 ${this.enhancedName(this.armor)}<br>💍 ${this.enhancedName(this.accessory)}</div><div class="exploreHint">移動ボタンで探索。敵・宝箱・階段・ショップを探す。</div>`;[['装備',()=>this.showEquipment()],['アイテム',()=>this.showItems()],['セーブ',()=>this.saveGame()],['ロード',()=>this.loadGame()]].forEach(([n,fn])=>{let b=document.createElement('button');b.textContent=n;b.onclick=fn;this.menuEl.appendChild(b)})}
 move(dx,dy){if(this.screen_mode==='password')return;if(this.screen_mode==='title'){if(dy!==0){this.title_index=this.title_index?0:1;this.drawAll()}return}if(this.screen_mode!=='game'||this.in_battle||this.in_shop)return;if(dx===1)this.player_direction='right';if(dx===-1)this.player_direction='left';if(dy===-1)this.player_direction='up';if(dy===1)this.player_direction='down';let nx=this.player[0]+dx,ny=this.player[1]+dy;if(this.isWall(nx,ny)){this.log('壁があって進めない。');this.drawAll();return}this.player=[nx,ny];let hit=this.getEnemyAt(nx,ny);if(hit){this.startBattle(hit);return}if(this.shop&&this.shop[0]===nx&&this.shop[1]===ny){this.enterShop();return}let tr=this.getTreasureAt(nx,ny);if(tr){this.treasures=this.treasures.filter(t=>t!==tr);this.log(this.openTreasure());this.enemyPhase();this.drawAll();return}if(this.stairs[0]===nx&&this.stairs[1]===ny){if(this.floor>=9){this.floor=10;this.startBossEvent(['よくぞたどりついたな。','昇給か？\nほしけりゃくれてやる。','この私を倒せたならなあ！'],()=>this.startIdeBattle());return}else{this.floor++;this.fade(()=>this.newFloor(),this.floorName(),'探索開始');return}}this.enemyPhase();this.drawAll()}
 enemyPhase(){this.enemies.forEach(e=>{if(e.freeze_turns&&e.freeze_turns>0){e.freeze_turns--;return}if(Math.random()<0.35)return;let dx=Math.sign(this.player[0]-e.x),dy=Math.sign(this.player[1]-e.y);let opts=Math.abs(this.player[0]-e.x)>Math.abs(this.player[1]-e.y)?[[dx,0],[0,dy]]:[[0,dy],[dx,0]];for(const [mx,my] of opts){let nx=e.x+mx,ny=e.y+my;if(!this.isWall(nx,ny)&&!this.enemies.some(o=>o!==e&&o.x===nx&&o.y===ny)&&!(this.shop&&this.shop[0]===nx&&this.shop[1]===ny)){e.x=nx;e.y=ny;break}}});let hit=this.getEnemyAt(this.player[0],this.player[1]);if(hit)this.startBattle(hit)}
 openTreasure(){let roll=Math.random();if(roll<.35){let g=rnd(35,85)+this.floor*8;this.gold+=g;return `宝箱を開けた。\n${g}Gを手に入れた。`}if(roll<.55){this.potions++;return '宝箱を開けた。\n回復薬を手に入れた。'}if(roll<.7){this.bombs++;return '宝箱を開けた。\n爆弾を手に入れた。'}if(roll<.82){this.smokes++;return '宝箱を開けた。\n煙玉を手に入れた。'}let item=this.randomEquip();this.addEquip(item);return `宝箱を開けた。\n${item.name}を手に入れた。`}
 randomEquip(){let tier=this.equipTier();let pools=[WEAPONS,ARMORS,ACCESSORIES];let p=choice(pools);return clone(choice(p.filter(i=>i.tier<=tier||i.rare)||p))}
 addEquip(item){if(item.atk!==undefined)this.inventory_weapons.push(item);else if(item.def!==undefined)this.inventory_armors.push(item);else this.inventory_accessories.push(item)} equipTier(){return this.floor<=3?1:this.floor<=6?2:this.floor<=9?3:4}
 setupBattle(enemy){this.in_battle=true;this.enemy=enemy;this.enemy_hp=enemy.hp;this.enemy_max_hp=enemy.hp;this.enemy_atk=enemy.atk;this.player_guard=false;this.player_skip_turn=false;this.enemy_turn_count=0;this.enemy_defending=false;this.player_turn=true;this.battle_result_mode=false;this.pending_result_text='';this.log(`${enemy.name}が現れた！\n戦闘開始。\nカワグチくんのターン。`)}
async startBattle(enemy){await this.fade(()=>this.setupBattle(enemy),'戦闘開始',`${enemy.name}が現れた！`,180);this.drawAll()}
 battleCommand(i){if(!this.in_battle||this.battle_result_mode||!this.player_turn)return;[()=>this.playerAttack(),()=>this.playerSpecial(),()=>this.playerDefend(),()=>this.showBattleItems(),()=>this.showEquipment(),()=>this.tryEscape()][i]()}
 shake(ms=280){if(!this.canvas)return;this.canvas.classList.remove('shake');void this.canvas.offsetWidth;this.canvas.classList.add('shake');setTimeout(()=>this.canvas&&this.canvas.classList.remove('shake'),ms)}

 shakeScreen(ms=280){
   // 敵の攻撃を受けた時は、キャンバスだけでなくHUDも一緒に揺らす。
   // #gameWrap 自体はスマホ縦画面で transform: scale(...) を使っているため、
   // そこを直接揺らすと拡大率が消える。内側の要素を揺らす。
   const targets=[
     document.getElementById('gameCanvas'),
     document.getElementById('hud')
   ].filter(Boolean);
   for(const t of targets){
     t.classList.remove('screenShake');
     void t.offsetWidth;
     t.classList.add('screenShake');
   }
   setTimeout(()=>targets.forEach(t=>t.classList.remove('screenShake')),ms);
 }

 delay(ms){return new Promise(res=>setTimeout(res,ms))}
 async playerAttack(){this.player_turn=false;let action='カワグチくんの攻撃！';let dmg=Math.max(1,rnd(this.atk-3,this.atk+6));if(this.enemy_defending)dmg=Math.max(1,Math.floor(dmg/2));this.enemy_defending=false;let gain=10;if(this.accessory?.id==='special_ring')gain=Math.floor(gain*(1+this.accessoryLevelValue(this.accessory)/100));this.special=Math.min(100,this.special+gain);this.log(action);this.drawAll();await this.delay(400);this.shake(280);await this.delay(430);this.enemy_hp-=dmg;if(this.enemy_hp<=0)return this.winBattle(`${action}\n${dmg}ダメージ！`);this.log(`${dmg}ダメージ！`);this.drawAll();setTimeout(()=>this.enemyTurn(),500)}
 async playerSpecial(){if(this.special<100){this.log('必殺ゲージが足りない。\nカワグチくんのターン。');this.drawAll();return}this.player_turn=false;this.special=0;let action='エクシオブレイカー！！';let dmg=rnd(45,65)+this.level*2;if(this.enemy_defending)dmg=Math.max(1,Math.floor(dmg/2));this.enemy_defending=false;this.log(action);this.drawAll();await this.delay(400);this.shake(340);await this.delay(490);this.enemy_hp-=dmg;if(this.enemy_hp<=0)return this.winBattle(`${action}\n${dmg}ダメージ！`);this.log(`${dmg}ダメージ！`);this.drawAll();setTimeout(()=>this.enemyTurn(),650)}
 playerDefend(){this.player_turn=false;this.player_guard=true;this.enemy_defending=false;this.special=Math.min(100,this.special+5);this.log('ぼうぎょ！\nこのターンのダメージを半減する。');this.drawAll();setTimeout(()=>this.enemyTurn(),500)}
 showBattleItems(){this.openModal('戦闘アイテム',[[`回復薬 x${this.potions}`,'kaihukuyaku',()=>this.usePotion()], [`爆弾 x${this.bombs}`,'bomb',()=>this.useBomb()], [`煙玉 x${this.smokes}`,'kemuridama',()=>this.useSmoke()]],'閉じる')}
 async usePotion(){if(this.potions<=0)return;this.closeModal();this.potions--;let old=this.hp;this.player_turn=false;this.log('回復薬を使った。');this.drawAll();await this.delay(600);this.hp=Math.min(this.max_hp,this.hp+50);this.log(`HPが${this.hp-old}回復した。`);this.drawAll();setTimeout(()=>this.enemyTurn(),800)}
 async useBomb(){if(this.bombs<=0)return;this.closeModal();this.bombs--;this.player_turn=false;let action='爆弾を投げた！';let dmg=45;this.enemy_defending=false;this.log(action);this.drawAll();await this.delay(400);this.shake(360);await this.delay(510);this.enemy_hp-=dmg;if(this.enemy_hp<=0)return this.winBattle(`${action}\n${dmg}ダメージ！`);this.log(`${dmg}ダメージ！`);this.drawAll();setTimeout(()=>this.enemyTurn(),500)}
 freezeEscapedEnemy(turns=4){if(this.enemy&&!this.enemy.boss)this.enemy.freeze_turns=turns}
useSmoke(){if(this.smokes<=0||this.enemy?.boss)return;this.closeModal();this.smokes--;this.freezeEscapedEnemy();this.fade(()=>{this.endBattle(false);this.log('煙玉を使って逃げ切った。\n敵はしばらくこちらを見失った。')},'', '',120)}
 tryEscape(){this.player_turn=false;if(this.enemy?.boss){this.log('魔王からは逃げられない！');this.drawAll();return setTimeout(()=>this.enemyTurn(),500)}if(Math.random()<.65){this.freezeEscapedEnemy();this.fade(()=>{this.endBattle(false);this.log('逃げ切った。\n敵はしばらくこちらを見失った。')},'', '',120)}else{this.log('逃げられなかった。');this.drawAll();setTimeout(()=>this.enemyTurn(),500)}}
 async enemyAttack(mult=1,msg=null){let action=msg||`${this.enemy.name}の攻撃！`;let base=rnd(this.enemy_atk-3,this.enemy_atk+4);let dmg=Math.max(1,Math.floor(base*mult)-this.defense);if(this.accessory?.id==='guard_ring')dmg=Math.max(1,dmg-this.accessoryLevelValue(this.accessory));if(this.player_guard)dmg=Math.max(1,Math.floor(dmg/2));this.log(action);this.drawAll();await this.delay(400);this.shakeScreen(280);await this.delay(430);this.hp-=dmg;this.special=Math.min(100,this.special+15);if(this.hp<=0)return this.gameOver();this.log(`${dmg}ダメージ！`);this.drawAll();setTimeout(()=>this.finishEnemyAction(),650)}
 enemyTurn(){if(!this.in_battle||!this.enemy)return;this.enemy_turn_count++;let id=this.enemy.id;if(id==='aya')return Math.random()<.55?this.enemyAttack():this.enemyNothing('アヤネルはこちらの様子をうかがっている。');if(id==='mura')return Math.random()<.55?this.enemyAttack():this.enemyNothing('ゴブリン村田は英語でなにやらまくしたてている。');if(id==='tani'){let p=this.enemy_turn_count%3;return p===1?this.enemyAttack():p===2?this.enemyNothing('反社タニオカはチカラをためている。'):this.enemyAttack(1.5,'反社タニオカの猛攻！')}if(id==='abe'){if(this.enemy_turn_count%3===0)return this.enemyBind();return Math.random()<.65?this.enemyAttack():this.enemyDefend()}if(id==='mae')return Math.random()<.65?this.enemyAttack():this.enemyDefend();if(id==='kane'){let r=Math.random();return r<.18?this.enemySteal():r<.72?this.enemyAttack():this.enemyDefend()}if(id==='kuri'){return this.enemy_hp<=this.enemy_max_hp*.35&&Math.random()<.55?this.enemyHeal():Math.random()<.65?this.enemyAttack():this.enemyDefend()}if(id==='jun')return this.enemy_turn_count%3===0?this.enemyAttack(1.5,'火のついたタバコを押し当ててきた！'):Math.random()<.65?this.enemyAttack():this.enemyDefend();if(id==='haya')return Math.random()<.45?this.enemyAttack():Math.random()<.75?this.enemyAttack(1.5,'痛風魔人ハヤノの猛攻！'):this.enemyDefend();if(id==='ide')return this.enemy_turn_count%5===0?this.enemyFixed('イデスラッシュ',40):Math.random()<.45?this.enemyAttack():Math.random()<.78?this.enemyAttack(1.5,'社長イデランの猛攻！'):this.enemyDefend();if(id==='ide2')return this.enemy_turn_count%5===0?this.enemyFixed('イデブラスター',70):Math.random()<.68?this.enemyAttack(1.5,'真・魔王イデランの猛攻！'):this.enemyDefend();return this.enemyAttack()}
 enemyNothing(m){this.log(m);this.finishEnemyAction()} enemyDefend(){this.enemy_defending=true;this.log(`${this.enemy.name}は身を守っている。`);this.finishEnemyAction()} enemyBind(){this.player_skip_turn=true;this.log('プラズマの長い髪がカワグチくんに絡みついた！');this.finishEnemyAction()} enemySteal(){let st=[];if(this.potions>0)st.push(['回復薬','potions']);if(this.bombs>0)st.push(['爆弾','bombs']);if(this.smokes>0)st.push(['煙玉','smokes']);if(!st.length){this.log('チッ、アイテム持ってないじゃん。シケてらぁ。');return this.finishEnemyAction()}let [n,a]=choice(st);this[a]--;this.log(`アイテムを盗もうとしてきた！\n${n}を盗まれた！`);this.finishEnemyAction()} async enemyHeal(){let old=this.enemy_hp;this.log('栗谷さんは食パンを食べた！');this.drawAll();await this.delay(600);this.enemy_hp=Math.min(this.enemy_max_hp,this.enemy_hp+35);this.log(`HPが${this.enemy_hp-old}回復した！`);this.drawAll();setTimeout(()=>this.finishEnemyAction(),800)} async enemyFixed(name,amount){let action=`${this.enemy.name}の必殺「${name}」！`;let dmg=this.player_guard?Math.max(1,Math.floor(amount/2)):amount;this.log(action);this.drawAll();await this.delay(400);this.shakeScreen(360);await this.delay(510);this.hp-=dmg;this.special=Math.min(100,this.special+20);if(this.hp<=0)return this.gameOver();this.log(`${dmg}ダメージ！`);this.drawAll();setTimeout(()=>this.finishEnemyAction(),650)}
 async finishEnemyAction(){this.player_guard=false;if(this.enemy?.id==='haya'){this.log('ハヤノは痛風で苦しんでいる！');this.drawAll();await this.delay(300);this.shake(280);await this.delay(430);this.enemy_hp-=5;if(this.enemy_hp<=0)return this.winBattle('痛風の痛みに耐えきれなかった！');this.log('5ダメージ！');this.drawAll();await this.delay(650)}if(this.accessory?.id==='heal_ring'&&this.hp<this.max_hp){this.log(`${this.enhancedName(this.accessory)}が光った！`);this.drawAll();await this.delay(600);let old=this.hp;this.hp=Math.min(this.max_hp,this.hp+this.accessoryLevelValue(this.accessory));this.log(`HPが${this.hp-old}回復した！`);this.drawAll();await this.delay(850)}if(this.player_skip_turn){this.player_skip_turn=false;this.log('髪が絡みついて、カワグチくんは身動きできない！');this.drawAll();return setTimeout(()=>this.enemyTurn(),700)}this.player_turn=true;this.drawAll()}
 winBattle(first){let id=this.enemy.id;if(id==='ide'){this.in_battle=false;this.enemy=null;this.startIde2Event();return}if(id==='ide2'){this.showEnding();return}let exp=12+this.floor*5,gold=rnd(25,50)+this.floor*6;this.exp+=exp;this.gold+=gold;let lines=[first,`${this.enemy.name}を倒した！`,`EXP +${exp}　${gold}G`];while(this.exp>=this.next_exp){this.exp-=this.next_exp;this.level++;this.next_exp+=15;this.max_hp+=10;this.atk_base+=2;this.def_base+=1;this.hp=this.max_hp;lines.push('レベルアップ！')}this.pending_result_text=lines.filter(Boolean).join('\n');this.battle_result_mode=true;this.player_turn=false;this.defeated_enemy=this.enemy;this.enemy=null;this.drawAll()}
 finishBattleResult(){this.fade(()=>{if(this.defeated_enemy)this.enemies=this.enemies.filter(e=>e!==this.defeated_enemy);this.defeated_enemy=null;this.in_battle=false;this.battle_result_mode=false;this.enemy=null;this.log('探索に戻った。')},'', '',120)} endBattle(){this.in_battle=false;this.enemy=null;this.player_turn=true;this.battle_result_mode=false;this.drawAll()} gameOver(){this.in_battle=false;this.in_shop=false;this.enemy=null;this.screen_mode='gameover';this.drawAll()}
 enterShop(){this.in_shop=true;this.log('ショップに入った。');this.drawAll()}
 showBuy(){let tier=this.equipTier();let items=[
 ['回復薬 30G','kaihukuyaku',()=>this.confirmBuyConsumable('回復薬','potion',30)],
 ['爆弾 80G','bomb',()=>this.confirmBuyConsumable('爆弾','bomb',80)],
 ['煙玉 60G','kemuridama',()=>this.confirmBuyConsumable('煙玉','smoke',60)],
 ...WEAPONS.filter(i=>i.tier===tier).map(i=>[`${i.name} ${this.itemPrice(i,'weapon')}G`,'sword',()=>this.confirmBuyEquip(i,'weapon')]),
 ...ARMORS.filter(i=>i.tier===tier).map(i=>[`${i.name} ${this.itemPrice(i,'armor')}G`,'armor',()=>this.confirmBuyEquip(i,'armor')]),
 ...ACCESSORIES.filter(i=>i.tier<=tier).map(i=>[`${i.name} ${this.itemPrice(i,'accessory')}G`,'ring',()=>this.confirmBuyEquip(i,'accessory')])];this.openModal('買う',items,'戻る')}
 itemPrice(item,kind){let base=kind==='weapon'?120+item.tier*90:kind==='armor'?100+item.tier*80:150+item.tier*70;if(item.rare)base=260;return base}
 itemDesc(item,kind){if(kind==='potion')return 'HPを50回復する。戦闘中に使える基本の回復アイテム。';if(kind==='bomb')return '敵に固定で60ダメージを与える。強敵への切り札。';if(kind==='smoke')return '戦闘から逃げる。逃げられない場面では失敗する。';return item?.desc||''}
 itemKind(item){if(!item)return '';if(item.atk!==undefined)return 'weapon';if(item.def!==undefined)return 'armor';return 'accessory'}
 itemPower(item){if(!item)return 0;if(item.atk!==undefined)return item.atk+this.enhanceBonus(item);if(item.def!==undefined)return item.def+this.enhanceBonus(item);if(item.id==='power_ring')return this.accessoryLevelValue(item);if(item.id==='special_ring')return this.accessoryLevelValue(item);if(item.id==='guard_ring')return this.accessoryLevelValue(item);if(item.id==='heal_ring')return this.accessoryLevelValue(item);return 0}
 compareHtml(item,kind,mode='buy'){
   if(kind==='weapon'){let cur=this.weapon?this.itemPower(this.weapon):0, nxt=this.itemPower(item)+(mode==='enhance'?2:0);return `<div class="compareTitle">装備比較</div><div>攻撃</div><div>${cur>=0?'+':''}${cur}　→　${nxt>=0?'+':''}${nxt}</div>`}
   if(kind==='armor'){let cur=this.armor?this.itemPower(this.armor):0, nxt=this.itemPower(item)+(mode==='enhance'?2:0);return `<div class="compareTitle">装備比較</div><div>防御</div><div>${cur>=0?'+':''}${cur}　→　${nxt>=0?'+':''}${nxt}</div>`}
   if(kind==='accessory'){
     let label=item.id==='power_ring'?'攻撃':item.id==='special_ring'?'必殺ゲージ':item.id==='guard_ring'?'被ダメージ軽減':'毎ターン回復';
     let cur=(this.accessory&&this.accessory.id===item.id)?this.itemPower(this.accessory):0;
     let nxt=this.itemPower(item)+(mode==='enhance'?(item.id==='special_ring'?10:item.id==='heal_ring'?3:2):0);
     let unit=item.id==='special_ring'?'%':'';
     return `<div class="compareTitle">効果比較</div><div>${label}</div><div>${cur}${unit}　→　${nxt}${unit}</div>`
   }
   return ''
 }
 confirmShop(title,item,kind,price,onYes,mode='buy'){
   const icon=(kind==='potion'?'kaihukuyaku':kind==='bomb'?'bomb':kind==='smoke'?'kemuridama':item.icon)||'gold';
   const name=typeof item==='string'?item:this.enhancedName(item);
   const desc=this.itemDesc(item,kind);
   const question=mode==='sell'?`${name}を\n${price}Gで売りますか？`:mode==='enhance'?`${name}を\n${price}Gで強化しますか？`:`${name}を\n${price}Gで買いますか？`;
   const comp=(kind==='weapon'||kind==='armor'||kind==='accessory')?this.compareHtml(item,kind,mode):'';
   this.modal.hidden=false;
   this.modal.innerHTML=`<h2>${title}</h2><div class="confirmTop">${this.assets[icon]?`<img src="${assetPath(icon)}">`:''}<div class="confirmQuestion">${question.replace(/\n/g,'<br>')}</div></div><div class="descBox"><b>説明</b><br>${desc}</div>${comp?`<div class="compareBox">${comp}</div>`:''}<div class="moneyLine">所持金：${this.gold}G</div>`;
   let acts=document.createElement('div');acts.className='modalActions';let yes=document.createElement('button');yes.textContent='はい';yes.onclick=onYes;let no=document.createElement('button');no.textContent='戻る';no.onclick=()=>this.closeModal();acts.append(yes,no);this.modal.appendChild(acts)
 }
 notEnough(){this.modal.hidden=false;this.modal.innerHTML=`<h2>確認</h2><div class="confirmTop"><img src="${assetPath('gold')}"><div class="confirmQuestion">お金が足りない。</div></div><div class="modalActions"><button id="neBack">戻る</button></div>`;this.modal.querySelector('#neBack').onclick=()=>this.closeModal()}
 confirmBuyConsumable(name,kind,price){this.confirmShop('購入確認',name,kind,price,()=>this.buyConsumable(kind,price,name),'buy')}
 confirmBuyEquip(item,kind){let price=this.itemPrice(item,kind);this.confirmShop('購入確認',item,kind,price,()=>this.buyEquip(item,kind),'buy')}
 buyConsumable(kind,price,name='アイテム'){if(this.gold<price)return this.notEnough();this.gold-=price;if(kind==='potion')this.potions++;if(kind==='bomb')this.bombs++;if(kind==='smoke')this.smokes++;this.closeModal();this.log(`${name}を買った。`);this.drawAll()}
 buyEquip(item,kind){let price=this.itemPrice(item,kind);if(this.gold<price)return this.notEnough();this.gold-=price;let cp=clone(item);this.addEquip(cp);this.closeModal();this.log(`${item.name}を買った。`);this.drawAll()}
 showSell(){let rows=[];this.inventory_weapons.filter(i=>i!==this.weapon).forEach(i=>rows.push([`${this.enhancedName(i)} ${Math.floor(this.itemPrice(i,'weapon')*.45)}G\n${i.desc}`,'sword',()=>this.confirmSell(i,'weapon')]));this.inventory_armors.filter(i=>i!==this.armor).forEach(i=>rows.push([`${this.enhancedName(i)} ${Math.floor(this.itemPrice(i,'armor')*.45)}G\n${i.desc}`,'armor',()=>this.confirmSell(i,'armor')]));this.inventory_accessories.filter(i=>i!==this.accessory).forEach(i=>rows.push([`${this.enhancedName(i)} ${Math.floor(this.itemPrice(i,'accessory')*.45)}G\n${i.desc}`,'ring',()=>this.confirmSell(i,'accessory')]));this.openModal('売る',rows.length?rows:[['売れるものがない','gold',()=>{}]],'戻る')}
 confirmSell(item,kind){let price=Math.floor(this.itemPrice(item,kind)*.45);this.confirmShop('売却確認',item,kind,price,()=>this.sell(item,kind),'sell')}
 sell(item,kind){let price=Math.floor(this.itemPrice(item,kind)*.45);this.gold+=price;if(kind==='weapon')this.inventory_weapons=this.inventory_weapons.filter(i=>i!==item);if(kind==='armor')this.inventory_armors=this.inventory_armors.filter(i=>i!==item);if(kind==='accessory')this.inventory_accessories=this.inventory_accessories.filter(i=>i!==item);this.closeModal();this.log(`${this.enhancedName(item)}を売った。`);this.drawAll()}
 showEnhance(){let rows=[];[...this.inventory_weapons,...this.inventory_armors,...this.inventory_accessories].forEach(i=>{let kind=this.itemKind(i);let stat=kind==='weapon'?`現在 強化 +${this.enhanceLevel(i)*2}　→　強化 +${this.enhanceLevel(i)*2+2}`:kind==='armor'?`現在 強化 +${this.enhanceLevel(i)*2}　→　強化 +${this.enhanceLevel(i)*2+2}`:`現在 ${this.itemPower(i)}　→　強化後`;rows.push([`${this.enhancedName(i)}　${i===this.weapon||i===this.armor||i===this.accessory?'装備中　':''}${this.enhanceCost(i)}G\n${stat}\n${i.desc}`,i.icon,()=>this.confirmEnhance(i)])});this.openModal('強化',rows,'戻る')}
 enhanceCost(i){return 80+(this.enhanceLevel(i)+1)*70+(i.tier||1)*30}
 confirmEnhance(i){let c=this.enhanceCost(i);let kind=this.itemKind(i);this.confirmShop('強化確認',i,kind,c,()=>this.enhanceItem(i),'enhance')}
 enhanceItem(i){let c=this.enhanceCost(i);if(this.gold<c)return this.notEnough();this.gold-=c;i.enhance=(i.enhance||0)+1;this.closeModal();this.log(`${this.enhancedName(i)}に強化した。`);this.drawAll()}
 showItems(){this.openModal('アイテム',[[`回復薬 x${this.potions}\n${this.itemDesc(null,'potion')}`,'kaihukuyaku',()=>{}],[`爆弾 x${this.bombs}\n${this.itemDesc(null,'bomb')}`,'bomb',()=>{}],[`煙玉 x${this.smokes}\n${this.itemDesc(null,'smoke')}`,'kemuridama',()=>{}]],'閉じる')}
 showEquipment(){let rows=[];this.inventory_weapons.forEach(i=>rows.push([`武器 ${i===this.weapon?'装備中 ':''}${this.enhancedName(i)} / 攻撃+${this.itemPower(i)}\n${i.desc}`,'sword',()=>{this.weapon=i;this.closeModal();this.log(`${this.enhancedName(i)}を装備した。`);this.drawAll()}]));this.inventory_armors.forEach(i=>rows.push([`防具 ${i===this.armor?'装備中 ':''}${this.enhancedName(i)} / 防御+${this.itemPower(i)}\n${i.desc}`,'armor',()=>{this.armor=i;this.closeModal();this.log(`${this.enhancedName(i)}を装備した。`);this.drawAll()}]));this.inventory_accessories.forEach(i=>rows.push([`装飾 ${i===this.accessory?'装備中 ':''}${this.enhancedName(i)} / ${i.effect}\n${i.desc}`,'ring',()=>{this.accessory=i;this.closeModal();this.log(`${this.enhancedName(i)}を装備した。`);this.drawAll()}]));this.openModal('装備',rows,'閉じる')}
 saveGame(){let keys=['floor','level','exp','next_exp','max_hp','hp','atk_base','def_base','special','player_direction','gold','potions','bombs','smokes','weapon','armor','accessory','inventory_weapons','inventory_armors','inventory_accessories'];let data={};keys.forEach(k=>data[k]=this[k]);localStorage.setItem(SAVE_KEY,JSON.stringify(data));this.log('セーブしました。');this.drawAll()}
 loadGame(){let raw=localStorage.getItem(SAVE_KEY);if(!raw){alert('セーブデータがありません。');return}Object.assign(this,JSON.parse(raw));this.in_battle=false;this.in_shop=false;this.enemy=null;this.game_cleared=false;this.screen_mode='game';this.newFloor();this.log('ロードしました。');this.drawAll()}
 submitPassword(){let p=(this.passwordInput?.value||'').trim();if(p===PASSWORD){sessionStorage.setItem('exio_pw_ok','1');this.passwordOk=true;this.screen_mode='title';if(this.passwordInput)this.passwordInput.value='';this.drawAll()}else{if(this.passwordError)this.passwordError.textContent='パスワードが違います。';if(this.passwordInput){this.passwordInput.select();this.passwordInput.focus();}}}
 titleConfirm(){if(this.screen_mode==='password'){this.submitPassword();return}if(this.title_index===0){this.initState();this.newFloor();this.screen_mode='opening';this.opening_index=0;this.drawAll()}else this.loadGame()}
 advanceOpening(){this.opening_index++;if(this.opening_index>=4){this.fade(()=>{this.screen_mode='game';this.log('ラーズビル攻略開始。最上階を目指せ。')},this.floorName(),'探索開始',420);return}this.drawAll()}
 startBossEvent(texts,next){this.event_texts=texts;this.event_index=0;this.event_next=next;this.screen_mode='boss_event';this.drawAll()} advanceBossEvent(){this.event_index++;if(this.event_index>=this.event_texts.length){let n=this.event_next;this.event_next=null;this.fade(()=>n&&n(),'', '',320);return}this.drawAll()} startIdeBattle(){this.screen_mode='game';let e=this.createEnemy({id:'ide',name:'社長イデラン',hp:220,atk:26,boss:true},this.player);this.startBattle(e)} startIde2Event(){this.startBossEvent(['なかなかやるな。\n\nだが、これで私に勝てたと\n思うなよ。','私の本当の姿を\n見せてやろう！'],()=>this.startIde2Battle())} startIde2Battle(){this.screen_mode='game';let e=this.createEnemy({id:'ide2',name:'真・魔王イデラン',hp:320,atk:32,boss:true},this.player);this.startBattle(e)} showEnding(){this.fade(()=>{this.in_battle=false;this.in_shop=false;this.enemy=null;this.game_cleared=true;this.screen_mode='ending'},'', '',360)}
 leftKey(){if(this.in_shop)return;if(this.screen_mode==='title')return;if(this.in_battle)return;this.move(-1,0)} rightKey(){if(this.screen_mode==='title')return;if(this.in_battle)return;this.move(1,0)} enterKey(){if(this.screen_mode==='password'||this.screen_mode==='title')return this.titleConfirm();if(this.screen_mode==='opening')return this.advanceOpening();if(this.screen_mode==='boss_event')return this.advanceBossEvent();if(this.screen_mode==='gameover'||this.screen_mode==='ending'){this.screen_mode='title';this.drawAll();return}} escKey(){if(this.in_shop){this.in_shop=false;this.drawAll()}}
 canvasClick(e){if(this.screen_mode==='password'||this.screen_mode==='title')return this.titleConfirm();if(this.screen_mode==='opening')return this.advanceOpening();if(this.screen_mode==='boss_event')return this.advanceBossEvent();if(this.screen_mode==='gameover'||this.screen_mode==='ending'){this.screen_mode='title';this.drawAll()}}
 openModal(title,rows,closeLabel){this.modal.hidden=false;this.modal.innerHTML=`<h2>${title}</h2>`;rows.forEach(([text,icon,fn])=>{let b=document.createElement('button');b.className='rowBtn';b.innerHTML=`${this.assets[icon]?`<img src="${assetPath(icon)}">`:''}<span>${text}</span>`;b.onclick=fn;this.modal.appendChild(b)});let acts=document.createElement('div');acts.className='modalActions';let close=document.createElement('button');close.textContent=closeLabel||'閉じる';close.onclick=()=>this.closeModal();acts.appendChild(close);this.modal.appendChild(acts)} closeModal(){this.modal.hidden=true;this.modal.innerHTML=''}
 fade(action,title='',sub='',hold=260){return new Promise(res=>{document.getElementById('fadeTitle').textContent=title;document.getElementById('fadeSub').textContent=sub;this.fadeEl.hidden=false;requestAnimationFrame(()=>{this.fadeEl.style.opacity='1';setTimeout(()=>{if(action)action();this.drawAll();this.fadeEl.style.opacity='0';setTimeout(()=>{this.fadeEl.hidden=true;res()},520)},hold+520)})})}
}

window.addEventListener('DOMContentLoaded',()=>{window.game=new Game()});
